
name: submit

on:
  workflow_dispatch:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Create submission folder
        shell: bash
        run: |
          echo $PWD
          mkdir -p submission
          cd ./submission/
          echo $PWD
          mkdir NetID1_NetID2_dpgen
          echo $PWD
          pushd .
          cd ..
          ls
          popd
          cp -r ../src ./NetID1_NetID2_dpgen/
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: submission
          draft: false
          prerelease: false
        
        
